---
name: ci-casper-trie

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt, clippy

      - name: Fmt
        uses: actions-rs/cargo@v1
        with:
          command: --locked
          args: fmt -- --check

      - name: Audit
        uses: actions-rs/cargo@v1
        with:
          command: --locked
          args: audit --deny warnings

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: --locked
          args: clippy --all-targets -- -D warnings

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: --locked
          args: test
